### ISSUE TITLE
add(optimism-state-bridge push-based mechanism)

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/world-id-contracts#25]
The current [optimism-state-bridge](https://github.com/worldcoin/optimism-state-bridge) design has a push-based mechanism that would send the latest state root along with its timestamp each time it is reconstructed due to a new batch insertion. This info would be sent to a relay contract which would call a method that triggers the L1<>L2 messenger to send that state root along with its timestamp to Optimism to use for World ID verification on the L2. 

### TODO:

- [x] figure out what branch to rebase the PR for this issue on
- [x] modify the world-id-contracts to send the latest state root and its timestamp to a specified contract which would forward that info to L2 (this is a forward-thinking design that would allow for a pull-based approach down the line)
- [ ] integration test by deploying setup on Ethereum and Optimism Goerli testnets
- [ ] testing with `verifyProof()` in `world-id-contracts@op-bridge/src/Semaphore.sol` @kustosz

**Comment by dcbuild3r** [comment]
Additional requisites:
- [ ] upgradable contracts for bridge and L2 WorldID
