### ISSUE TITLE
add(support for multiple chains)

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/world-id-contracts#26]
Propagate the latest root hashes and timestamps to many different rollups, validiums, and other scaling solutions. 

### Requirements 
- [ ] [Switch from pull-based to push-based approach](https://github.com/worldcoin/optimism-state-bridge/issues/3) ([spec](https://github.com/worldcoin/optimism-state-bridge/blob/main/spec.md))

### TODO

- [ ] Add methods on proxy contract to abstract L1<>L2 communication with all supported chains
- [ ] Build a public entry method from world-id-contracts that will call the methods for the other chains, passing the latest state root hashes and timestamps from the external service
- [ ] Add monitoring to make sure data hits all the target contracts on L2s
- [ ] Bonus: Make the service call a chain-specific contract method if L1<>L2 comms fail

**Comment by dcbuild3r** [comment]
this will most likely not be pursued as storage proofs are looking like a viable alternative. re: [Herodotus](https://github.com/orgs/worldcoin/projects/4/views/herodotus.dev) integration. 

Right now the `world-id-state-bridge` contracts support Optimism and Polygon for launch. However, the next iteration will most likely use storage proofs. List of [supported networks by Herodotus](https://docs.herodotus.dev/herodotus-docs/supported-networks)

**Comment by dcbuild3r** [comment]
Interesting candidates for OmniChain WorldID integrations:
- [Herodotus](https://herodotus.dev/) (L1<>L2 comms, snarkified storage proofs)
- [Axiom](https://axiom.xyz/) (L1<>L2 comms)
- [Succinct](https://twitter.com/SuccinctLabs/status/1636429568172228609?s=20) (Telepathy L1<>L1 comms)
